### PR TITLE
Add idempotent_id to chat and threads services

### PR DESCRIPTION
**Pull request by ben-toogood**

### CODE REVIEW

**Comment by asim** [comment]
Would just call it ID rather than idempotent id as we'd just expect all IDs to be idempotent and defined by the caller.

**Comment by ben-toogood** [comment]
> Would just call it ID rather than idempotent id as we'd just expect all IDs to be idempotent and defined by the caller.

I'm not a fan of having the primary ID defined by the user. I've seen this done before and it's caused issues where some users generate IDs which are much shorter or longer than expected.

**Comment by asim** [comment]
If you don't want the user to define the ID then I'd imagine an API or client, web or mobile app would sit in front of the service doing that for you. If you want to ensure users of services provide valid IDs then maybe just check that its a uuid and error out otherwise? But I'd still expect the ID to be defined by the caller and be the thing that's idempotent. Feels weird to define an "idempotent_id".

**Comment by ben-toogood** [comment]
Okay, will amend

**Pull request merged**
