### PR TITLE
WIP: Replace model with store in RSS service

### PR DESCRIPTION
**Pull request by h1z3y3**
Replace model with Store.

But sacrificed the `date order` feature in `Feed` function. Any good idea?

Close https://github.com/micro/services/issues/314

### CODE REVIEW

**Comment by asim** [comment]
It's unfortunate, I still need to add indexing/filtering/orderBy to the micro store itself. When that's done date ordering would be easy enough. Otherwise we would probably have to add date to the key for ordering to work properly. I think if the entry key has a date suffix like then it might work. so rss/feed/[url]/[id]/[date]

**Comment by h1z3y3** [comment]
@asim I have three questions:

1. I wonder if any Store types will support all the features, like `limit()` `offset()` ? No matter `memory` or `file`.
2. Does Store support RDB ? like `mysql` ?
3. Can you tell me more about why replace model/db with Store ?

**Comment by asim** [comment]
1. All store implementations must support the features including limit and offset. Consistency is important.
2. We are using postgres as the underlying store in production but with a fixed data format. See the plugin https://github.com/micro/micro/tree/master/plugin/postgres
3. The model was written on top of the store to be a convenient abstraction but has been a bit clunky to use along with being inefficient just due to the use of the store rather than a separate indexing store. So we're replacing it until we rewrite the model. The DB is a service offered to end customers but has been used for the user service, this means the data is openly accessible by them which could lead to many long term issues. Once we have every service uniformly using the store we can then start to address what the next storage layer might look like or rebuilding a sql model with a cleaner interface in micro.

**Comment by h1z3y3** [comment]
Thank you very much for your detailed explanation ！

**Comment by h1z3y3** [comment]
Sorry, I haven't finish the migration script. 
So are there any needs to migrate old data?

**Comment by asim** [comment]
No, I think the usage is bare minimal if not zero so I've truncated the data.

**Comment by asim** [comment]
The user service will require migration though

**Pull request merged**
