### PR TITLE
FIX: userId -> user_id

### PR DESCRIPTION
**Pull request by hrand1005**
Snake case fields conforms to .proto style guide and is consistent with the rest of the file.
Style Guide: https://developers.google.com/protocol-buffers/docs/style

### CODE REVIEW

**Comment by asim** [comment]
This service is already in use. This is a breaking change. You also haven't recompiled the proto.

**Comment by cyb3rko** [comment]
Maybe those kind of changes could be collected in a seperate directory to prepare v2 of services?
Because ignoring changes because it's in production is maybe not the best way to go.

**Comment by asim** [comment]
I agree, equally we just need to check what the current usage looks like and whether to hard break. I agree that it's highlighting a path to v2, the question is just how v2 coincides with client and api changes e.g is it /v2/service/endpoint in m3o as well?

**Comment by cyb3rko** [comment]
Why hard breaking the production when going for a new version is possible too?
I would say `/v2/service/endpoint` is pretty straight-forward.

**Comment by asim** [comment]
It's not straight forward. We have 1 deployment of a service, regardless. So we'd have to start deploying separate versions and then have to deploy a separate v2 gateway for that and then even the way we display docs would have to be versioned.

**Comment by cyb3rko** [comment]
Oh, I see what you mean.
That's a lot of work :(

**Comment by asim** [comment]
Yes, now @lambdaR has already started work on v2 clients, but I think to do an entire v2 means really working on the full pipeline. I think v2 has to take other things into consideration like making it possible to route to APIs that are not just on the platform but anywhere.

**Pull request closed without merging**
