### PR TITLE
Proposal to add new feature to the user endpoint - Passwordless

### PR DESCRIPTION
**Pull request by lambdaR**
Passwordless will allow you to login in using just an email, the service will send a link to the submitted email and once the owner clicks the link the service will publish new message which contains session to the specified topic.

### CODE REVIEW

**Comment by asim** [comment]
I think the idea of passwordless login is sound. The naming of endpoints might change and the implementation itself. e.g SendMagicLink and VerifyToken or something of that nature. I think also topic shouldn't be a thing we put in the request because it exposes implementation details. Instead you want something like ID, and it might be more appropriate to store in the cache or similar for a given TTL.

**Comment by lambdaR** [comment]
Hi @asim 
Did some changes to the code as your suggestions (see the commit) 
Code needs some refactoring though.

**Comment by asim** [comment]
Will come back and review this soon

**Comment by asim** [comment]
Might ask @crufter or @domwong also to have a look

**Comment by lambdaR** [comment]
What I’m trying to achieve here is when the user clicks the login button the user/SendMagicLink  kicks in with an email as payload, then it does the necessary checks and after that it subscribes to a topic (currently this code uses the old stream and m3o now has three new options: new stream, mq and events). The login page won’t update/redirect until the m3o client receives a session object which indicates that the user has clicked the MagicLink sent to his/her email.

There are some issues here with the link itself, currently when the user clicks the MagicLink it will redirect him/her to a page that shows “not authorized” message i believe because i didn’t attach M3O user API token with the MagicLink, so i think we need some sort of 3rd party app that consume the link instead then publish to the topic.

**Comment by domwong** [comment]
Taking a high level look, I like the approach in general; I like the use of the broker for pubsub. Need to be wary of leaking goroutines though so need to make sure to break out of the loop after some timeout. Thumbs up from me in that it's definitely something worth progressing but will need a proper review and testing - @crufter might be better placed for that

**Comment by asim** [comment]
I'd like to get this merged this week. @lambdaR can you please resolve the conflicts then we'll review and merge.

**Comment by lambdaR** [comment]
Since M3O will introduce App hosting soon, I am leaning toward the idea of removing the VerifyToken endpoint and replace it with passworldless.m3o.com App instead, basically a web server that receives a request from the link that have been sent to user’s email, do the necessary checks and display green check symbol if successful or a red X if the token was invalid or any failed checks. 

In short, converting the VerifyToken endpoint to a web server hosted on passworldless.m3o.com.

**Comment by asim** [comment]
We have user.m3o.com for any app based stuff for verification, but equally apis should be standalone and the functionality shouldn't depend on third party apps that we can't guarantee will exist

**Comment by lambdaR** [comment]
What 3rd party? M3O should provision and maintain the passworldless.m3o.com in this case and it is dedicated only to the Passwordless feature proposed.

**Comment by asim** [comment]
This repo is totally separate to any form of hosting. If the API itself or the endpoints are not useful without a UI then its an issue

**Comment by lambdaR** [comment]
Ok, Is there a chance that M3O can internally provide a mechanism to generate a one time token (token for accessing endpoints)? In this way we can send to the user an email with a link that holds two tokens, one for accessing (one time access) the VerifyToken endpoint and the second one to authorize access for the account.

**Comment by asim** [comment]
There is an otp service in this repo you can call for that

**Comment by lambdaR** [comment]
I will keep this branch for my personal use and move the PR to  #292

**Pull request closed without merging**
