### PR TITLE
Fix not returning "nanoid" as available ID type

### PR DESCRIPTION
**Pull request by cyb3rko**
For context see https://github.com/micro/services/pull/420#issuecomment-1185778952

### CODE REVIEW

**Comment by cyb3rko** [comment]
@asim I have no idea if the fix was correct but the changes don't work until now.

Is the fix just not live yet or did I miss something?

**Comment by cyb3rko** [comment]
I see, I didn't rerun proto on this one.
My bad...

**Comment by asim** [comment]
Feels like we need something that automatically does it for minor changes

**Comment by asim** [comment]
But this shouldn't require a proto rerun

**Comment by cyb3rko** [comment]
Does something like that exist?
Ah, works now.

**Comment by asim** [comment]
Service was in a crash loop, had to kill and redeploy it

**Pull request merged**
