### PR TITLE
BugFix: if name == "" should return the prefix key

### PR DESCRIPTION
**Pull request by h1z3y3**
1. Without the condition,  if name is empty string, the key always be `rss/feed/micro/admin/14695981039346656037`，
So the `List()` which use `prefix` to search will return `[]`
2. fix limit is not working

### CODE REVIEW

**Comment by asim** [comment]
Let me know when its ready to merge

**Comment by h1z3y3** [comment]
It's ready now, I found some bugs when I did tests. 
Please merge , thanks .

**Comment by asim** [comment]
Deployed

**Comment by h1z3y3** [comment]
> Deployed

I've done all APIs tests, there is no problem.  😆

**Comment by asim** [comment]
Thanks!

**Pull request merged**
